[deploy] support other env dotfiles
Signed-off-by: Carlos Nunez <13461447+carlosonunez@users.noreply.github.com>

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -1,8 +1,14 @@
 #!/usr/bin/env bash
 
 # shellcheck disable=SC2046
-test -e "$(dirname "$0")/../.env" &&
-  eval $(sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g" "$(dirname "$0")/../.env")
+ENV_FILE="${ENV_FILE:-$(dirname "$0")/../${ENV_FILE}}"
+if ! test -e "$ENV_FILE"
+then
+  >&2 echo "ERROR: Env file not found: $ENV_FILE"
+  exit 1
+fi
+eval $(sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g" "${ENV_FILE}")
+unset AWS_SESSION_TOKEN
 
 set -e
 export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID?Please define AWS_ACCESS_KEY_ID.}"
@@ -14,7 +20,7 @@ ENVIRONMENT="${ENVIRONMENT:-test}"
 DEPLOY_FUNCTIONS_ONLY="${DEPLOY_FUNCTIONS_ONLY:-false}"
 
 >&2 echo "INFO: Logging into AWS; please stand by."
-session_name="slack-apis-deploy-$(date +%s)"
+session_name="slack-status-bot-deploy-$(date +%s)"
 export AWS_SESSION_NAME="$session_name"
 if ! aws_session_info=$(docker-compose -f docker-compose.deploy.yml run -T --rm obtain-aws-session-token)
 then
