Fail if not 200

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -13,5 +13,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Perform status updates
-        run: "curl --fail-with-body -X POST -H 'X-API-Key: ${{ secrets.status_api_key }}' '${{ secrets.status_url }}'"
+        run: >-
+          file=$(mktemp);
+          code=$(curl -X POST -H 'X-API-Key: ${{ secrets.status_api_key }}' \
+            -o "$file" -w '%{http_code}' '${{ secrets.status_url }}');
+          body=$(cat "$file");
+          rm -f "$file";
+          if [ "$code" != 200 ];
+          then >&2 echo "ERROR: Update failed with [$code]: $body";
+          fi;
 
